Do not overwrite snapshot if error in reading
Dewberry/process-api pull request #20
Opened 2023-04-27 16:13 UTC by ar-siddiqui

2023-04-27 21:20 UTC, slawler requested changes

2023-04-27 21:20 UTC, slawler commented on handlers/config.go
> +			log.Info("Starting with clean Jobs cache.")
We should add a flag option to overwrite __or__ create a new database, and have this error inform the user of this option.

2023-05-04 15:06 UTC, ar-siddiqui commented on handlers/config.go
> +			log.Info("Starting with clean Jobs cache.")
Option added.

2023-05-04 20:10 UTC, slawler approved these changes
Thanks!

2023-05-04 20:49 UTC, merged