Readme and Snapshot
Dewberry/process-api pull request #21
Opened 2023-04-27 20:29 UTC by ar-siddiqui

2023-04-27 21:33 UTC, slawler requested changes

2023-04-27 21:33 UTC, slawler commented on README.md
> -Example processes are provided in [plugins/](plugins/) directory.
Please add explicit language regarding plugins so that they are clearly differentiable to processes

2023-05-04 15:40 UTC, ar-siddiqui commented on README.md
> -Example processes are provided in [plugins/](plugins/) directory.
Please see line 17. It does mention plugins that are in essence just `processing_directory`?

2023-05-04 22:51 UTC, ar-siddiqui commented
@slawler please approve

2023-05-10 17:00 UTC, merged